{% set name = "beautysh" %}
{% set version = "6.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9df2fd6584f2470fcb76556ac0bf4c69575133d63318a1d8e4253a064cc145e1
    folder: dist
  - url: https://github.com/lovesegfault/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 16830490343a9bdb30e0b9cc994dec735114cfd4ba7c69b4545ff7e287df48b3
    folder: src

build:
  noarch: python
  number: 1
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - beautysh = beautysh.beautysh:main

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - setuptools

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
  imports:
    - beautysh
  commands:
    - beautysh --version
    - beautysh --help
    - python -m pip check
    # coverage 61% as of 6.0.1
    - cd src && pytest --cov beautysh --cov-fail-under 60

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
