{% set name = "beautysh" %}
{% set version = "4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 738b712c0a8141dd77fed50db70d1de415adf3d86f0f272abfb5b1f76af5f1e7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - beautysh = beautysh.beautysh:main

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3

test:
  imports:
    - beautysh
  commands:
    - beautysh --help

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - bemeurer
    - bollwyvl
