{% set name = "beautysh" %}
{% set version = "5.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01d992bc9616b4b097145d5c6d11f7d779351ea45a4ea48ec809fa9b81cca879

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - beautysh = beautysh.beautysh:main

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - setuptools

test:
  imports:
    - beautysh
  commands:
    - beautysh --version
    - beautysh --help

about:
  home: https://github.com/bemeurer/beautysh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Bash beautifier for the masses.

extra:
  recipe-maintainers:
    - lovesegfault
    - bollwyvl
    - dbast
