travis:
  secure:
    BINSTAR_TOKEN: pBj+Kgbi040ZpxpEX7w4jIZvFctxhTCUeGmlfByzBsbMHTgz8eIDIg8kfuXlTgaY9qV/WgGtI5WheWcQ4saPNjbQRA7AY8J8YqTo0ULrtb3z/vc6g1B/ejG1HgyCItY/iqJP7XGyvhj8SqLDHQkeTdf3cIeQokVx/p5c4Ecp0EvtxsUp4u+8XESyl5Nd+TwTYiMCJPomYiXGBZJqkhsBqbQNZ0ah9unANr/cb2ua3jg4PY5Wa/17um/39ntUM2kcRTmCLbMaQCd8KBlwoyvHWDbQ+skC3tTbqnwIFmnO2Hx8z2u9fnfjUzN7Q/qxadCbkMhg1O0f+j6sZwX1ojitEZ+n43Y/X2vntgl9uruoEOwXMmqdUdaz7hw8Zi9e2JpkHO/TzqXxf8KeLnlT+ZN1j+jJyWliokcilidwg54OWrEmNflV0bhkbLmmpeWJ8PirED2uRhMvxxzlOquhAM8ZiomO8D5DpfV1sS4FFBTNKkdSzAt2KEhFcRBvu8bshyij02eY0iedzCb5Q4FkH9Fh29r/GbV2Oqo8KcEtCFF3sAvanG9zxW/esT8rf693bB92XiGf6Dn/e9sodZlUU43e43x8Zjxo8FV2hFioc+PhAsXzevMuFKXHFBR9QqBYMzj1AWea73jckGYTxEUdu2z+TGl8LI1aPa9wwLGw8fXSXnA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
